config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
    redirect_to flat_path(@flat.id)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat.id)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.input :description %>
  <%= f.submit "Add place", class: "btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">

  <h1>Edit <%= @flat.name %></h1>

  <%= render "form", flat: @flat %>

</div>

app/views/flats/index.html.erb
<div class="container">

  <h1 class="title" >All our flats</h1>
  <p>All <%= @flats.count %> flats</p>

  <div class="row">

    <% @flats.each do |flat| %>
      <div class="col-4">
        <%# this is a flat card %>
        <div class="my-card">
          <%# picture %>
          <%= image_tag(flat.image) %>


          <%# general info %>
          <div class="general-info">
            <h3><%= flat.name %></h3>
            <p><%= flat.address %></p>

            <div class="guest-price">
              <i class="fa-solid fa-people-group"></i>
              <p class="no-margin"><%= flat.number_of_guests %></p>
              <i class="fa-solid fa-euro-sign"></i>
              <p class="no-margin"><%= flat.price_per_night %></p>
            </div>
          </div>

          <%# action buttons %>
          <div class="action-buttons">
            <%= link_to "More info", flat_path(flat.id) %>
            <%= link_to "Edit", edit_flat_path(flat.id) %>
            <%= link_to "Delete", flat_path(flat.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          </div>

        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/flats/new.html.erb
<div class="container">

  <h1>Add a new place to rent</h1>

  <%= render "form", flat: @flat %>

</div>

app/views/flats/show.html.erb
<div class="banner">
</div>

<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="card">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>
      <div class="card">
        <h3>A little more about this place...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>

    <div class="col-4">
      <div class="card">
        <h4>Book this place!</h4>
        <button class="btn btn-success">Book</button>
      </div>
      <div class="card">
        <h4>Details</h4>
        <p><%= @flat.number_of_guests %> people   <%= @flat.price_per_night %>€</p>
      </div>
      <div class="card">
      </div>
    </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="navvbar">
      <%= link_to "Simple Airbnb", flats_path, class: "prim my-btn" %>
      <%= link_to "Add flat", new_flat_path, class: "sec my-btn" %>
    </div>

    <%= yield %>
  </body>
</html>